export enum OrderListMyActionTypes {
  ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST",
  ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS",
  ORDER_LIST_MY_FAILURE = "ORDER_LIST_MY_FAILURE",
  ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET",
}
