export enum OrderPayActionTypes {
  ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAILURE = "ORDER_PAY_FAILURE",
  ORDER_PAY_RESET = "ORDER_PAY_RESET",
}
