import { UserRegisterState } from "./";
import { UserLoginState } from "./";
import { CartState } from "./";
import { ProductDetailsState } from "./";
import { ProductListState } from "./";
import { UserDetailsState } from "./";
import { OrderCreateState } from "./OrderCreate";
import { OrderDeliverState } from "./OrderDeliver";
import { OrderDetailsState } from "./OrderDetails";
import { OrderListState } from "./OrderList";
import { OrderListMyState } from "./OrderListMy";
import { OrderPayState } from "./OrderPay";
import { ProductCreateState } from "./ProductCreate";
import { ProductCreateReviewState } from "./ProductCreateReview";
import { ProductDeleteState } from "./ProductDelete";
import { ProductTopState } from "./ProductTop";
import { ProductUpdateState } from "./ProductUpdate";
import { UserDeleteState } from "./UserDelete";
import { UserListState } from "./UserList";
import { UserUpdateState } from "./UserUpdate";
import { UserUpdateProfileState } from "./UserUpdateProfile";

export interface ReduxState {
  userLogin: UserLoginState;
  userRegister: UserRegisterState;
  productList: ProductListState;
  productDetails: ProductDetailsState;
  cart: CartState;
  userDetails: UserDetailsState;
  userUpdateProfile: UserUpdateProfileState;
  orderCreate: OrderCreateState;
  orderDetails: OrderDetailsState;
  orderPay: OrderPayState;
  orderDeliver: OrderDeliverState;
  orderListMy: OrderListMyState;
  orderList: OrderListState;
  userList: UserListState;
  userDelete: UserDeleteState;
  userUpdate: UserUpdateState;
  productDelete: ProductDeleteState;
  productCreate: ProductCreateState;
  productUpdate: ProductUpdateState;
  productCreateReview: ProductCreateReviewState;
  productTopRated: ProductTopState;
}
