export enum UserListActionTypes {
  USER_LIST_REQUEST = "USER_LIST_REQUEST",
  USER_LIST_SUCCESS = "USER_LIST_SUCCESS",
  USER_LIST_FAILURE = "USER_LIST_FAILURE",
  USER_LIST_RESET = "USER_LIST_RESET",
}
